steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/britestack-email-function', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/britestack-email-function']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'britestack-email-function'
      - '--image'
      - 'gcr.io/$PROJECT_ID/britestack-email-function'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'SENDGRID_API_KEY=${_SENDGRID_API_KEY}'

images:
  - 'gcr.io/$PROJECT_ID/britestack-email-function'

substitutions:
  _SENDGRID_API_KEY: ''
